import json
from datetime import datetime


def generate_evidence_package(compliance_result: dict, equipment_id: str) -> dict:
    """
    Convert a compliance_engine result into a structured, auditable evidence package.
    This is NOT the same as the conversational answer — it's a structured record
    suitable for audit trail purposes, with explicit timestamping and traceability.
    """
    package = {
        "package_type": "compliance_evidence_package",
        "generated_at": datetime.now().isoformat(),
        "equipment_id": equipment_id,
        "analysis_confidence": compliance_result.get("confidence"),
        "sources_reviewed": compliance_result.get("sources", []),
        "full_narrative_analysis": compliance_result.get("answer"),
        "disclaimer": (
            "This package was generated by an AI compliance assistant. "
            "CONFIRMED findings are direct verifications against retrieved regulation text. "
            "RISK_SIGNAL findings are inferences from patterns, not verified violations. "
            "This package requires human safety officer review before use in a formal audit."
        )
    }
    return package


def save_evidence_package(package: dict, filepath: str):
    with open(filepath, "w") as f:
        json.dump(package, f, indent=2)
    print(f"Evidence package saved to {filepath}")
    